# Generated by Django 4.1.7 on 2023-03-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=30)),
                ('method', models.CharField(max_length=30)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]