# Generated by Django 4.1.7 on 2023-03-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0002_firstmodellog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name_plural': 'Logs'},
        ),
    ]